// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeED4tVvqSPE0kiFdKyGSX_4uLmE3243A',
    appId: '1:412540779109:web:0d98fe455e811503e2e48c',
    messagingSenderId: '412540779109',
    projectId: 'book-base-31262',
    authDomain: 'book-base-31262.firebaseapp.com',
    storageBucket: 'book-base-31262.firebasestorage.app',
    measurementId: 'G-5SFL3P08HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZvggHuLh9pK0c06FNWLgsX7wMwNFW3c',
    appId: '1:412540779109:android:cc251e57f9660661e2e48c',
    messagingSenderId: '412540779109',
    projectId: 'book-base-31262',
    storageBucket: 'book-base-31262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW4nxEBJCQk7Vk579hp0OmXTcAuClsrWc',
    appId: '1:412540779109:ios:c0a0bea60b1efaf6e2e48c',
    messagingSenderId: '412540779109',
    projectId: 'book-base-31262',
    storageBucket: 'book-base-31262.firebasestorage.app',
    iosBundleId: 'com.example.bookBase',
  );
}
